### PR TITLE
FIx warnings in all tools built in the CI

### LINKED ISSUE #189: Squash warnings of llu print from Kokkos Tools
Remove warnings of llu print from Kokkos . This is seen in the latest CI for Kokkos Tools.

### PR DESCRIPTION
**Pull request by masterleinad**
Fixes #189.

### CODE REVIEW

**Comment by vlkale** [comment]
Ah, thanks for going ahead and doing this! This LGTM and is how I was planning to fix.

**Comment by vlkale** [comment]
@masterleinad Thanks again here. It's strange - this isn't passing the simple build CI now? It was just a squash of warnings right?

**Comment by vlkale** [comment]
Ah sorry - I see this is a draft pull request. Perhaps there are some things in an intermediate state or still being worked on.

File: common/kokkos-sampler/kp_sampler_skip.cpp [hunk 1]
```diff
@@ -238,7 +244,7 @@ extern "C" {
 
 namespace impl = KokkosTools::Sampler;
 
-EXPOSE_TOOL_SETTINGS(kokkosp_request_tool_settings)
+EXPOSE_TOOL_SETTINGS(impl::kokkosp_request_tool_settings)
```
Comment (masterleinad) [inline common/kokkos-sampler/kp_sampler_skip.cpp:247]: This resulted in an infinite loop.

File: profiling/simple-kernel-timer/kp_json_writer.cpp [hunk 2]
```diff
@@ -79,18 +79,8 @@ int main(int argc, char* argv[]) {
...
-
         int commandline_args = 1;
         while( (commandline_args<argc ) && (argv[commandline_args][0]=='-') ) {
-          if(strcmp(argv[commandline_args],"--delimiter")==0) {
-            delimiter=argv[++commandline_args][0];
-          }
-          if(strcmp(argv[commandline_args],"--fixed-width")==0) {
-            fixed_width=atoi(argv[++commandline_args]);
-          }
-
```
Comment (masterleinad) [inline profiling/simple-kernel-timer/kp_json_writer.cpp:93]: These command line arguments were parsed but never used. I'm not quite sure if we want to keep them or not.

Comment (dalg24) [reply profiling/simple-kernel-timer/kp_json_writer.cpp:93]: No that is a leftover from starting from kp_reader.  I think I wrote that guy and the delimiter of fixed width does not make sense for JSON

File: profiling/simple-kernel-timer/kp_json_writer.cpp [hunk 3]
```diff
@@ -60,7 +60,7 @@ inline void write_json(std::ostream& os, KernelPerformanceInfo const& kp,
 int find_index(std::vector<KernelPerformanceInfo*>& kernels,
 	const char* kernelName) {
 
-	for(int i = 0; i < kernels.size(); i++) {
+	for(unsigned int i = 0; i < kernels.size(); i++) {
```
Comment (dalg24) [inline profiling/simple-kernel-timer/kp_json_writer.cpp:63]: I'd have gone for size_t but not blocking

File: common/kokkos-sampler/kp_sampler_skip.cpp (hunk 1 above)
Comment (vlkale) [reply common/kokkos-sampler/kp_sampler_skip.cpp:247]: @masterleinad Thanks for pointing this out! Do you have a particular code you tested this on that gave this result? 

By the way, I am currently creating test cases for all the tools connectors. (Also, from this, an idea I had is to create a generic tools utility and generic tools connector. This would address Kokkos Tools Github Issue #92 and make the development. ) This is a bigger effort but my focus is on the sampler. 

This fix you suggest should be part of a separate github PR.

Comment (masterleinad) [reply common/kokkos-sampler/kp_sampler_skip.cpp:247]: No, I didn't actually test it. This just gave compiler warnings (for this to result in an infinite loop which makes sense) and that's why I fix it here.

Comment (vlkale) [reply common/kokkos-sampler/kp_sampler_skip.cpp:247]: OK, got it.

That makes sense to put the fix in this PR.

Thanks.

**Review by crtrott — APPROVED** [review]
